[package]
org = "ballerina"
name = "graphql"
version = "1.2.2"
authors = ["Ballerina"]
keywords = ["gql", "network", "query", "service"]
repository = "https://github.com/ballerina-platform/module-ballerina-graphql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.1"

[[platform.java11.dependency]]
path = "../native/build/libs/graphql-native-1.2.2-SNAPSHOT.jar"
